// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3Rs4Z7ovkemI655wrzhEAS3DTfXHLC3Q',
    appId: '1:788823753711:web:ce68500351a73844746c1a',
    messagingSenderId: '788823753711',
    projectId: 'chater-d4ac8',
    authDomain: 'chater-d4ac8.firebaseapp.com',
    storageBucket: 'chater-d4ac8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoGvkwl4LL9MkJf8rz0FFK0EBkBnjw1UA',
    appId: '1:788823753711:android:6e2a0e1ff739e598746c1a',
    messagingSenderId: '788823753711',
    projectId: 'chater-d4ac8',
    storageBucket: 'chater-d4ac8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8obBo0wRUiXO_XzZnovbYfGKWMUtV3DA',
    appId: '1:788823753711:ios:67acfb7edb4beca3746c1a',
    messagingSenderId: '788823753711',
    projectId: 'chater-d4ac8',
    storageBucket: 'chater-d4ac8.appspot.com',
    iosBundleId: 'com.example.chater',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8obBo0wRUiXO_XzZnovbYfGKWMUtV3DA',
    appId: '1:788823753711:ios:1a24c03c02d733e2746c1a',
    messagingSenderId: '788823753711',
    projectId: 'chater-d4ac8',
    storageBucket: 'chater-d4ac8.appspot.com',
    iosBundleId: 'com.example.chater.RunnerTests',
  );
}
